### ISSUE TITLE
Overriding only behavior when vote is above threshold 

### ISSUE THREAD

**Issue by MarKco** [codemybrainsout/smart-app-rate#11]
Hello,
I imported the library and all is working. I noticed that when the vote is above the threshold te user is redirected to the Play Store page of the app, but there's no explicit prompt to ask him to rate the app again.
I'd like to put a dialog in the middle between the first app rating and the play store page, asking the user if he/she wants to rate the app on play store.

The question is: how can I achieve that?

Thank you
Marco

**Comment by codemybrainsout** [comment]
Hi, Use `onThresholdCleared()` method to perform your custom action when user rates above the threshold value.
Update your gradle dependency to `compile 'com.codemybrainsout.rating:ratingdialog:1.0.6'`

**Comment by ankushgupta1393** [comment]
Hey @MarKco, Were you able to achieve what you wanted? I want to do the same i.e.  I'd like to put a dialog in the middle between the first app rating and the play store page, asking the user if he/she wants to rate the app on play store. Like the one it's doing when rating is below threshold and also I don't want any rating bar.
