### ISSUE TITLE
wordwrap on feedback dialog

### ISSUE THREAD

**Issue by carcme** [codemybrainsout/smart-app-rate#13]
Hi,

Tiny issue... word wrap on the feedback form doesn't work. Text runs off the side of the screen

Simple change to the EditText "dialog_rating_feedback" 

android:layout_height="wrap_content"
...
android:inputType="textCapSentences|textMultiLine"
android:minLines="4"

Cheers

**Comment by ahulr** [comment]
Thanks @carcme I'll add this to the next update.
