### ISSUE TITLE
More customization of the dialogs

### ISSUE THREAD

**Issue by alexjcrowley** [codemybrainsout/smart-app-rate#18]
Would it be possible to get some more options for the dialog look? Such as being able to disable rounded corners, set dialog background colour, etc?

I really want to use this is in a project of mine instead of implementing it myself, but given I am using the material dialogs library the dialogs wouldn't match exactly.

**Comment by ahulr** [comment]
I'm sorry my busy schedule doesn't allow me to work much on this library but you are free to submit Pull requests and all the customizations that you suggest are most welcome.
