### ISSUE TITLE
How to reset the session?

### ISSUE THREAD

**Issue by kaustav07** [codemybrainsout/smart-app-rate#22]
if i give the `session(2)` the dialog shows up after 2 times the app opened, but after that it never shows, how to reset the session show it shows periodically after some number of times the app opened?

**Comment by ahulr** [comment]
Hi, If you click on 'Maybe Later' or dismiss the dialog by touching on the sides of the screen, the dialog will re-appear after 2 sessions. But if you click on 'Never', the dialog won't show again.
