### ISSUE TITLE
App icon picked-up is blurred

### ISSUE THREAD

**Issue by neutt22** [codemybrainsout/smart-app-rate#24]
Without me looking thru at the source code, I noticed that the produced icon is blurred and kind of unacceptable. How would I go about this?

I feed Android Studio 512x512 `ic_launcher` and it scales and divided them into screen qualifier directories.

**Comment by ahulr** [comment]
Hi, You can use the ```.icon(drawable)``` method of the dialog to set a high res icon.

**Comment by neutt22** [comment]
It doesn't accept mipmap?

**Comment by neutt22** [comment]
Nevermind, its okay now. Thanks!
