### ISSUE TITLE
Only show RatingDialog when internet is available

### ISSUE THREAD

**Issue by vit001** [codemybrainsout/smart-app-rate#27]
I have an app that is mostly used off-line. How can I disable showing the RatingDialog when a user is offline? There is no point in showing the RatingDialog when offline and it only frustrates users.

**Comment by alexjcrowley** [comment]
What I would do is create a TwoStageRate object using the standard builder pattern detailed in the README and then after that create a method for checking the internet connection (see: https://stackoverflow.com/questions/9570237/android-check-internet-connection) and then display if there is an internet connection.

Something like this:

```
TwoStageRate twoStageRate = .....

if (isInternetConnection) {
    twoStageRate.showIfMeetsConditions();
}
```

**Comment by ahulr** [comment]
@vit001 open the Dialog inside an if condition as mentioned by @alexjcrowley above.
