### ISSUE TITLE
Making the number of sessions available

### ISSUE THREAD

**Issue by zeray01** [codemybrainsout/smart-app-rate#28]
Hello, 
first let me thank you for this library! 
I want to make the rating dialog visible after a certain amount of app starts. Could you create a getter for the session counter, so it is accessible?
Thank you!

**Comment by alexjcrowley** [comment]
_"If you want the dialog to appear on the Nth session of the app, just add the session(N) to the dialog builder method and move the code to the onCreate() method of your Activity class. The dialog will appear when the app is opened for the Nth time."_ - README

Does this solve your issue? The library is intended to function in such a way that you don't need to worry about checking the session count.

**Comment by ahulr** [comment]
@zeray01 You don't have to worry about the session count. Just pass the desired session count in the `session(n)` function and the library will take care of the rest.
