### ISSUE TITLE
User voted, app still brings up the rating popup

### ISSUE THREAD

**Issue by icss91** [codemybrainsout/smart-app-rate#29]
Happens on Android 6.0.1 with 2 different phone models.

**Comment by ahulr** [comment]
@icss91 What value for `session(n)` are you using?

**Comment by mermazza** [comment]
@ahulr is the logo used in dialog free to use and without any copyright issue

**Comment by ahulr** [comment]
@mermazza The library automatically picks your app's icon and displays it in the dialog. The logo you mentioned is the icon for the sample app and is not included in the library.
