### ISSUE TITLE
Second button on the dialogs is white with white text and isn't visible

### ISSUE THREAD

**Issue by Photogad** [codemybrainsout/smart-app-rate#31]
Second button on the dialogs is white with white text and isn't visible
https://imgur.com/gallery/5xpny

**Comment by Photogad** [comment]
it's doing the same thing for the button on the intial popup with the stars.  the second button in bottom right corner is invisible

**Comment by grezzled** [comment]
set session(x) with x>1 .. it will shows up

```
final RatingDialog ratingDialog = new RatingDialog.Builder(this)
                .threshold(3)
                .session(2)// seesion count should be >1 
                .onRatingBarFormSumbit(new RatingDialog.Builder.RatingDialogFormListener() {
                    @Override
                    public void onFormSubmitted(String feedback) {
                    }
                }).build();

        ratingDialog.show();
```

**Comment by ahulr** [comment]
@photog0411 You can change both the text color and background color of the buttons using the respective methods.
