### ISSUE TITLE
where is the feedback alert. 

### ISSUE THREAD

**Issue by Ziaxp** [codemybrainsout/smart-app-rate#35]
Nothing is shown after clicking the stars. Where is the feedback alert when give 3 or less stars and even didn't go to Play Store if click 4 or 5 stars. And even it shows one button i.e. 'Not Now', where is the other button. See the code, and tell me whats wrong with it. And if need some amendments so please do it. Thanks.

                final RatingDialog ratingDialog = new RatingDialog.Builder(context)
                .icon(context.getResources().getDrawable(R.drawable.ic_rate_star))

                .threshold(3)
                .title("How was your experience with us?")
                .titleTextColor(R.color.black)
                .positiveButtonText("Not Now")
                .negativeButtonText("Never")
                .positiveButtonTextColor(R.color.main_orange_color)
                .negativeButtonTextColor(R.color.main_blue_color)
                .formTitle("Submit Feedback")
                .formHint("Tell us where we can improve")
                .formSubmitText("Submit")
                .formCancelText("Cancel")
                .ratingBarColor(R.color.main_orange_color)
                .playstoreUrl("https://play.google.com/store/apps/details?id=com.king.bubblewitch3&hl=en")
                .onThresholdCleared(new RatingDialog.Builder.RatingThresholdClearedListener() {
                    @Override
                    public void onThresholdCleared(RatingDialog ratingDialog, float rating, boolean thresholdCleared) {
                        //do something

                        ratingDialog.dismiss();
                    }
                })
                .onThresholdFailed(new RatingDialog.Builder.RatingThresholdFailedListener() {
                    @Override
                    public void onThresholdFailed(RatingDialog ratingDialog, float rating, boolean thresholdCleared) {
                        //do something

                        ratingDialog.dismiss();
                    }
                })
                .onRatingChanged(new RatingDialog.Builder.RatingDialogListener() {
                    @Override
                    public void onRatingSelected(float rating, boolean thresholdCleared) {
                        thresholdCleared = true;
                        Supporter.showToast(context, "rating is: " + rating);
                    }
                })
                .onRatingBarFormSumbit(new RatingDialog.Builder.RatingDialogFormListener() {
                    @Override
                    public void onFormSubmitted(String feedback) {

                    }
                }).build();

        ratingDialog.show();

**Comment by ahulr** [comment]
@Ziaxp Don't set `onThresholdCleared()` and `onThresholdFailed()` listeners if you want to use the default feedback form of the dialog and auto Google Play redirection.

https://github.com/codemybrainsout/smart-app-rate#note

**Comment by Ziaxp** [comment]
Great thanks it worked
