### ISSUE TITLE
Keyboard not shown automatically for feedback form

### ISSUE THREAD

**Issue by namannik** [codemybrainsout/smart-app-rate#36]
Thanks for creating this library.  It's working well with one small issue.  In my app, when the feedback form is shown, the keyboard doesn't automatically appear.  Instead, the user has to tap in the `EditText` field to force the keyboard to be displayed.  Is this the expected behavior?  If so, does the library provide a way to show the keyboard automatically?  If not, I think automatically displaying the keyboard would be a nice enhancement.

**Comment by ahulr** [comment]
@namannik Keyboard not showing up is the intended behavior. You can still open the keyboard by adding this code to the `onRatingChanged()` listener.

`InputMethodManager inputMethodManager (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
inputMethodManager.toggleSoftInputFromWindow(
    linearLayout.getApplicationWindowToken(),
    InputMethodManager.SHOW_FORCED, 0);`
