### ISSUE TITLE
Dilaog not showing on click event 

### ISSUE THREAD

**Issue by gssinghgautam** [codemybrainsout/smart-app-rate#4]
RatingDialog ratingDialog = new RatingDialog.Builder(this)
                        .threshold(3)
                        .onRatingBarFormSumbit(new RatingDialog.RatingDialogFormListener() {
                            @Override
                            public void onFormSubmitted(String feedback) {

                            }
                        }).build();

                ratingDialog.show();

this code not showing the dialog from click of button

**Comment by codemybrainsout** [comment]
This issue has been fixed. Please use the latest version in your dependencies.

`compile 'com.codemybrainsout.rating:ratingdialog:1.0.4'`
