### ISSUE TITLE
How to reset flags?

### ISSUE THREAD

**Issue by gcatak** [codemybrainsout/smart-app-rate#40]
You need to add a functionality to reset flags. It is not possible even though I create new object but flags was not reset.

**Comment by gcatak** [comment]
It is impossible to show again if I click "never" in my smartphone. Unwanted scenario for developers. As developers we love resetting flags.

**Comment by mercierj** [comment]
Kotlin :

val sharedpreferences = getSharedPreferences("RatingDialog", Context.MODE_PRIVATE)
        sharedpreferences.edit().clear().apply()

**Comment by juanla** [comment]
> It is impossible to show again if I click "never" in my smartphone. Unwanted scenario for developers. As developers we love resetting flags.

If an user choose "Never" you shouln't show more the rate dialog. Instead you can add an option in your app settings to rate and leave the user go to rate your app  manually

**Comment by mercierj** [comment]
> > It is impossible to show again if I click "never" in my smartphone. Unwanted scenario for developers. As developers we love resetting flags.
> 
> If an user choose "Never" you shouln't show more the rate dialog. Instead you can add an option in your app settings to rate and leave the user go to rate your app manually

I guess it's about testing purpose, as a dev, uninstalling the app each time you want to try something is kind of painfull.
Don't know why my answer has been downvoted, it does work, but again, it's just for testing purpose.

**Comment by ahulr** [comment]
You can use `resetCount()` added in [v2.0.0](https://github.com/codemybrainsout/smart-app-rate/releases/tag/2.0.0)
