### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Sub-Zero-1** [codemybrainsout/smart-app-rate#42]
Hi,

I have implemented this library into my app, but somehow it did not show up. I then installed your demo app and press like 100 times the "Rate us" button and it appeared just 2 times. Tried again, but nothing happend....Galaxy S9 Plus...

**Comment by Tsabary** [comment]
Yeah same, the window just doesn't come up

**Comment by veselinnguyen** [comment]
The same problem. First of all the session(N) does not work. Let's say N = 2. Opening the app 2 times will not trigger the dialog to show. Also missing Never option on the screen. It shows only Maybe later.
