### ISSUE TITLE
where is the option to change Accent color or background color?

### ISSUE THREAD

**Issue by PalashSachan** [codemybrainsout/smart-app-rate#44]
Hi,
i am unable to find option to change Accent color?
i tried changing my app theme accent color also but its not working.
currently its orange color coming as the background color
i want to change it
please help ASAP

Thanks

**Comment by iliaswo** [comment]
some problem

**Comment by abhi-9605** [comment]
Change dialog_rating.xml 
---------------------------------------------

<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#FFFFFF">

    <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:animateLayoutChanges="true"
            android:background="@null">

        <ImageView
                android:id="@+id/dialog_rating_icon"
                android:layout_width="100dp"
                android:layout_height="100dp"
                android:layout_centerHorizontal="true"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="10dp"
                android:layout_marginRight="15dp" />

        <TextView
                android:id="@+id/dialog_rating_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/dialog_rating_icon"
                android:layout_centerHorizontal="true"
                android:layout_marginLeft="15dp"
                android:layout_marginRight="15dp"
                android:gravity="center"
                android:padding="20dp"
                android:textSize="20sp" />

        <RatingBar
                android:id="@+id/dialog_rating_rating_bar"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@id/dialog_rating_title"
                android:layout_centerHorizontal="true"
                android:layout_marginLeft="15dp"
                android:layout_marginRight="15dp"
                android:numStars="5"
                android:scaleX="0.7"
                android:scaleY="0.7"
                android:stepSize="1" />

        <TextView
                android:id="@+id/dialog_rating_feedback_title"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="15dp"
                android:layout_marginRight="15dp"
                android:textColor="@color/black"
                android:textSize="18sp"
                android:visibility="gone" />

        <EditText
                android:id="@+id/dialog_rating_feedback"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:layout_below="@id/dialog_rating_feedback_title"
                android:layout_marginLeft="15dp"
                android:layout_marginTop="15dp"
                android:layout_marginRight="15dp"
                android:background="@drawable/edittext_background"
                android:gravity="top|left"
                android:inputType="textMultiLine|textCapSentences"
                android:lines="8"
                android:maxLines="10"
                android:minLines="6"
                android:padding="10dp"
                android:scrollbars="vertical"
                android:textColorHint="@color/grey_400"
                android:visibility="gone" />

        <LinearLayout
                android:id="@+id/dialog_rating_feedback_buttons"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/dialog_rating_feedback"
                android:layout_marginTop="15dp"
                android:orientation="horizontal"
                android:visibility="gone">

            <TextView
                    android:id="@+id/dialog_rating_button_feedback_cancel"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:clickable="true"
                    android:foreground="?attr/selectableItemBackground"
                    android:gravity="center"
                    android:padding="15dp"
                    android:textSize="15sp" />

            <TextView
                    android:id="@+id/dialog_rating_button_feedback_submit"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:clickable="true"
                    android:foreground="?attr/selectableItemBackground"
                    android:gravity="center"
                    android:padding="15dp"
                    android:textSize="15sp" />

        </LinearLayout>

        <LinearLayout
                android:id="@+id/dialog_rating_buttons"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@id/dialog_rating_rating_bar"
                android:layout_marginTop="15dp"
                android:orientation="horizontal">

            <TextView
                    android:id="@+id/dialog_rating_button_negative"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:background="?attr/selectableItemBackground"
                    android:clickable="true"
                    android:gravity="center"
                    android:padding="15dp"
                    android:textSize="15sp" />

            <TextView
                    android:id="@+id/dialog_rating_button_positive"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_weight="1"
                    android:background="?attr/selectableItemBackground"
                    android:clickable="true"
                    android:gravity="center"
                    android:padding="15dp"
                    android:textSize="15sp" />

        </LinearLayout>

    </RelativeLayout>

</ScrollView>
