### ISSUE TITLE
dialog keep showing even after clicking  on rated stars

### ISSUE THREAD

**Issue by HmimssaSoufiane** [codemybrainsout/smart-app-rate#49]
I already rated but  it keeps showing, you need to add two methods one with SharedPreferences to store that dialog has been rated and not showing again even you use without a session, and another method to force the dialog showing even after the click on rated ( that's needed if we won't add the dialog in a button click )

**Comment by JackyGohSG** [comment]
I'm running into the same issue as well. Did you managed to fix it?

**Comment by HmimssaSoufiane** [comment]
Non , I just changed it to another one i use [that](https://github.com/guy-4444/SmartRateUsDialog-Android)

**Comment by leeroyhero** [comment]
> I already rated but it keeps showing, you need to add two methods one with SharedPreferences to store that dialog has been rated and not showing again even you use without a session, and another method to force the dialog showing even after the click on rated ( that's needed if we won't add the dialog in a button click )

I think logic is if you are not set session or set it as 1 then you must handle showing by yourself
![11](https://user-images.githubusercontent.com/16205548/86511281-2cda4180-be00-11ea-9bfd-74c3a2b2043e.png)

**Comment by HmimssaSoufiane** [comment]
@leeroyhero  thanks but i used another approach

@gohkimnam  

###### declare this objects your activity ;
```java

    private SharedPreferences preferences;
    private SharedPreferences.Editor editor;
    private RatingDialog ratingDialog;

```
###### add this code to the onCreate methode
```java
        preferences = getApplicationContext().getSharedPreferences("RatingDialog", 0); // 0 - for private mode
        editor = preferences.edit();

        ratingDialog = new RatingDialog.Builder(this)
                .icon(ResourcesCompat.getDrawable(getResources(), R.drawable.ic_passionate, null))
                .ratingBarColor(R.color.yellow)
                .title("to get the full functionality of the app please rate us.")
                .threshold(3)
                .onRatingChanged(new RatingDialog.Builder.RatingDialogListener() {
                    @Override
                    public void onRatingSelected(float rating, boolean thresholdCleared) {
                        editor.putBoolean("RatingDialog_show", false); // Storing boolean - true/false
                        editor.commit();
                    }
                })
                .build();
        if (preferences.getBoolean("RatingDialog_show", true))
            ratingDialog.show();
```
###### the button
```java
        rateUs.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View v) {
                ratingDialog.show();

            }
        });
```
