### ISSUE TITLE
Feedback From

### ISSUE THREAD

**Issue by karopass** [codemybrainsout/smart-app-rate#6]
HI ! Thanks for awesome library. I am confused little.... Where should I write **My email address** for get Feedback that user write ? Sorry I am little new in android and trying to implement this awesome library in my project. Thanks

**Comment by rpattabi** [comment]
I haven't used this lib yet. But I don't think this library can send the email automatically on behalf of the user. You get the text and push it to your server may be.

**Comment by codemybrainsout** [comment]
Hi @karopass 

You can submit your feedback by starting the e-mail intent in the ```onFormSubmitted``` callback.
It should look something like this:

```java
@Override
public void onFormSubmitted(String feedback) {
    Intent i = new Intent(Intent.ACTION_SEND);
    i.setType("message/rfc822");
    i.putExtra(Intent.EXTRA_EMAIL  , new String[]{"recipient@example.com"});
    i.putExtra(Intent.EXTRA_SUBJECT, EMAIL_SUBJECT);
    i.putExtra(Intent.EXTRA_TEXT   ,feedback);
  try {
    startActivity(Intent.createChooser(i, "Send mail..."));
  } catch (android.content.ActivityNotFoundException ex) {
    Toast.makeText(MyActivity.this, "There are no email clients installed.", Toast.LENGTH_SHORT).show();
  }
}
```
