### ISSUE TITLE
Never Button

### ISSUE THREAD

**Issue by karopass** [codemybrainsout/smart-app-rate#7]
Hi ! I am using simple dialogue as you have mentioned...But I am not getting Never Button for dialogue....its only showing Maybe Later....How I can get also never button ? Thanks

**Comment by codemybrainsout** [comment]
Hi @karopass 
If you're opening the dialog on a click event or deliberately setting the session value to 1, the dialog won't show the never button. If you set the dialog to automatically appear on a defined session **e.g setting ```.session(4)```** the Never button will appear.
