### ISSUE TITLE
What if users rate with multiple clicks?

### ISSUE THREAD

**Issue by rpattabi** [codemybrainsout/smart-app-rate#8]
I am yet to use this library. From the information available, it looks like, there is one scenario this library may not have considered. 

In our usability testing, we have noticed some users rate with multiple clicks. You may laugh at this, but this is what we have seen them doing:

1. The user decided to rate the app 5 *s.
1. She started clicking on the first star, then 2nd, then 3rd.. (You get the idea).

She feels she is giving each of the stars to us one by one. :) I was totally surprised by this approach. The reason may be that large number of users are exposed to mobile interfaces, many of them don't have any exposure to desktop interfaces. But we developers, with strong background in desktop interface patterns, tend to get surprised when our app users don't follow standard patterns.

So how well this lib works for this scenario. Does it assume user gave 1 star and shows feedback form?

**Comment by codemybrainsout** [comment]
Yes clicking on the first star will open the feedback form because that's how the RatingBar is supposed to work. I think the scenario you're mentioning can be handled by proper communication with the user in the form of tutorials or showcase views.

**Comment by rpattabi** [comment]
Having an option to have a submit button will help address this problem.
