### ISSUE TITLE
Just rate item, not app

### ISSUE THREAD

**Issue by TommyQu** [codemybrainsout/smart-app-rate#9]
Can I use this library to rate the movie item on my app instead of the whole application? I also don't want open google play store after I rate.

**Comment by codemybrainsout** [comment]
Hi, You can use `onThresholdCleared()` and `onThresholdFailed()` methods to override default behavior of the dialog.
Update your gradle dependency to `compile 'com.codemybrainsout.rating:ratingdialog:1.0.6'`
